<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Text extends Model
{
    use HasFactory;

    public function addNew($data)
    {
              
        $allData = [

        'city_search'         => $data['city_search'],
        'city_locate'         => $data['city_locate'],
        'city_address'        => $data['city_address'],
        'land_mark'           => $data['land_mark'],
        'city_save'           => $data['city_save'],
        'search'              => $data['search'],
        'trend_in'            => $data['trend_in'],
        'exit_app'            => $data['exit_app'],
        'exit_app_desc'       => $data['exit_app_desc'],
        'exit_app_confirm'    => $data['exit_app_confirm'],
        'previous_order'      => $data['previous_order'],
        'sort_by'             => $data['sort_by'],
        'rating'              => $data['rating'],
        'nearest'             => $data['nearest'],
        'new_arrival'         => $data['new_arrival'],
        'km'                  => $data['km'],
        'per_person'         => $data['per_person'],
        'search_title'        => $data['search_title'],
        'search_res'          => $data['search_res'],
        'trend_search'        => $data['trend_search'],
        'menu_title'          => $data['menu_title'],
        'view_info'           => $data['view_info'],
        'delivery_time'       => $data['delivery_time'],
        'close_time'          => $data['close_time'],
        'store_close'         => $data['store_close'],
        'all'                 => $data['all'],
        'select_size'         => $data['select_size'],
        'req_addon'           => $data['req_addon'],
        'add_cart'            => $data['add_cart'],
        'add_cart_msg'        => $data['add_cart_msg'],
        'remove_cart_msg'     => $data['remove_cart_msg'],
        'rating_review'       => $data['rating_review'],
        'cart_title'          => $data['cart_title'],
        'cart_price'          => $data['cart_price'],
        'cart_qty'            => $data['cart_qty'],
        'have_discount'       => $data['have_discount'],
        'apply_here'          => $data['apply_here'],
        'sub_total'           => $data['sub_total'],
        'd_charges'           => $data['d_charges'],
        'discount'            => $data['discount'],
        'total_payable'       => $data['total_payable'],
        'checkout'            => $data['checkout'],
        'empty'               => $data['empty'],
        'start_shopping'      => $data['start_shopping'],
        'select_offer'        => $data['select_offer'],
        'apply'               => $data['apply'],
        'no_offer'            => $data['no_offer'],
        'remove'              => $data['remove'],
        'offer_applied'       => $data['offer_applied'],
        'cashback_msg'        => $data['cashback_msg'],
        'login_title'         => $data['login_title'],
        'login_email'         => $data['login_email'],
        'login_password'      => $data['login_password'],
        'login_button'        => $data['login_button'],
        'forgot_pass'         => $data['forgot_pass'],
        'dont_have'           => $data['dont_have'],
        'signup_now'          => $data['signup_now'],
        'login_validation'    => $data['login_validation'],
        'login_error'         => $data['login_error'],
        'signup_title'        => $data['signup_title'],
        'signup_desc'         => $data['signup_desc'],
        'signup_name'         => $data['signup_name'],
        'signup_phone'        => $data['signup_phone'],
        'signup_email'        => $data['signup_email'],
        'rcode'               => $data['rcode'],
        'signup_password'     => $data['signup_password'],
        'signup_btn'          => $data['signup_btn'],
        'signup_error'        => $data['signup_error'],
        'forgot_title'        => $data['forgot_title'],
        'forgot_text'         => $data['forgot_text'],
        'enter_email'         => $data['enter_email'],
        'reset'               => $data['reset'],
        'verify_email'        => $data['verify_email'],
        'enter_otp'           => $data['enter_otp'],
        'verify'              => $data['verify'],
        'new_pass'            => $data['new_pass'],
        'new_password'        => $data['new_password'],
        'confirm_password'    => $data['confirm_password'],
        'update_pass'         => $data['update_pass'],
        'otp_sent_msg'        => $data['otp_sent_msg'],
        'otp_validation'      => $data['otp_validation'],
        'new_pass_validation'  => $data['new_pass_validation'],
        'confirm_pass_validation' => $data['confirm_pass_validation'],
        'password_update_msg'     => $data['password_update_msg'],
        'order_type'          => $data['order_type'],
        'delivery'            => $data['delivery'],
        'pickup'              => $data['pickup'],
        'order_date_time'     => $data['order_date_time'],
        'deliver_today'       => $data['deliver_today'],
        'deliver_later'       => $data['deliver_later'],
        'select_date'         => $data['select_date'],
        'select_time'         => $data['select_time'],
        'select'              => $data['select'],
        'persoanl_info'       => $data['persoanl_info'],
        'name'                => $data['name'],
        'phone'               => $data['phone'],
        'address'             => $data['address'],
        'landmark'            => $data['landmark'],
        'comment'             => $data['comment'],
        'payment_method'      => $data['payment_method'],
        'cod'                 => $data['cod'],
        'stripe'              => $data['stripe'],
        'razor'               => $data['razor'],
        'stripe_title'        => $data['stripe_title'],
        'card_no'             => $data['card_no'],
        'exp_month'           => $data['exp_month'],
        'exp_year'            => $data['exp_year'],
        'cvv'                 => $data['cvv'],
        'book_now'            => $data['book_now'],
        'stripe_validation'   => $data['stripe_validation'],
        'stripe_config'       => $data['stripe_config'],
        'card_no_validation'  => $data['card_no_validation'],
        'apt_success'         => $data['apt_success'],
        'ref_no'              => $data['ref_no'],
        'total_amount'        => $data['total_amount'],
        'go_back'             => $data['go_back'],
        'address_add'         => $data['address_add'],
        'address_msg'         => $data['address_msg'],
        'ecash_desc'          => $data['ecash_desc'],
        'ecash'                 => $data['ecash'],
        'use_ecash'             => $data['use_ecash'],
        'no_running_order'      => $data['no_running_order'],
        'on_going_order'        => $data['on_going_order'],
        'order_from'            => $data['order_from'],
        'order_placed_text'     => $data['order_placed_text'],
        'order_confirmed_text'  => $data['order_confirmed_text'],
        'delivery_assign_text'  => $data['delivery_assign_text'],
        'order_on_way'          => $data['order_on_way'],
        'order_cancel_text'     => $data['order_cancel_text'],
        'order_no'              => $data['order_no'],
        'order_detail'          => $data['order_detail'],
        'call'                  => $data['call'],
        'welcome'               => $data['welcome'],
        'ref_code'              => $data['ref_code'],
        'ref_code_desc'         => $data['ref_code_desc'],
        'account_title'             => $data['account_title'],
        'my'                        => $data['my'],
        'lang_setting'              => $data['lang_setting'],
        'change_location'           => $data['change_location'],
        'back_home'                 => $data['back_home'],
        'logout'                    => $data['logout'],
        'order_date'                => $data['order_date'],
        'status'                    => $data['status'],
        'item'                      => $data['item'],
        'qty'                       => $data['qty'],
        'price'                     => $data['price'],
        'no_order'                  => $data['no_order'],
        'cancel_order'              => $data['cancel_order'],
        'cancel_order_confirm'         => $data['cancel_order_confirm'],
        'cancel_order_confirm_desc'    => $data['cancel_order_confirm_desc'],
        'rating_title'                 => $data['rating_title'],
        'rating_des'                   => $data['rating_des'],
        'submit_btn'                   => $data['submit_btn'],
        'menu_welcome'                 => $data['menu_welcome'],
        'menu_home'                    => $data['menu_home'],
        'menu_my'                      => $data['menu_my'],
        'menu_my_account'              => $data['menu_my_account'],
        'menu_lang'                    => $data['menu_lang'],
        'menu_location'                => $data['menu_location'],
        'running_order'                => $data['running_order'],
        'menu_about'                   => $data['menu_about'],
        'menu_faq'                     => $data['menu_faq'],
        'menu_contact'                 => $data['menu_contact'],
        'lang_title'                   => $data['lang_title'],
        'update_lang'                  => $data['update_lang'],
        'd_login_phone'                => $data['d_login_phone'],
        'd_home_title'                 => $data['d_home_title'],
        'd_active'                     => $data['d_active'],
        'd_offline'                    => $data['d_offline'],
        'd_no_order'                   => $data['d_no_order'],
        'd_order_id'                   => $data['d_order_id'],
        'd_user'                       => $data['d_user'],
        'd_phone'                      => $data['d_phone'],
        'd_address'                    => $data['d_address'],
        'd_view_detail'                => $data['d_view_detail'],
        'd_accept'                     => $data['d_accept'],
        'd_show_dir'                   => $data['d_show_dir'],
        'd_order_item'                 => $data['d_order_item'],
        'd_other_info'                 => $data['d_other_info'],
        'd_total_amount'               => $data['d_total_amount'],
        'd_payment_method'             => $data['d_payment_method'],
        'd_cod'                        => $data['d_cod'],
        'd_online'                     => $data['d_online'],
        'd_ecash_paid'                 => $data['d_ecash_paid'],
        'd_paid_ecash'                 => $data['d_paid_ecash'],
        'd_total_pay'                  => $data['d_total_pay'],
        'd_start_ride'                 => $data['d_start_ride'],
        'd_complete_ride'              => $data['d_complete_ride'],
        'd_confirm'                    => $data['d_confirm'],
        'd_order_start'                => $data['d_order_start'],
        'd_order_delivered'            => $data['d_order_delivered'],
        'd_account_title'              => $data['d_account_title'],
        'd_my_order'                   => $data['d_my_order'],
        'd_change_pass'                => $data['d_change_pass'],
        's_dont_have'                  => $data['s_dont_have'],
        's_signup_now'                 => $data['s_signup_now'],
        's_signup_title'               => $data['s_signup_title'],
        's_signup_desc'                => $data['s_signup_desc'],
        's_signup_name'                => $data['s_signup_name'],
        's_signup_phone'               => $data['s_signup_phone'],
        's_signup_address'             => $data['s_signup_address'],
        's_signup_pass'                => $data['s_signup_pass'],
        's_submit'                     => $data['s_submit'],
        's_order_overview'             => $data['s_order_overview'],
        's_total_order'                => $data['s_total_order'],
        's_complete_order'             => $data['s_complete_order'],
        's_new_order'                  => $data['s_new_order'],
        's_canceled_order'             => $data['s_canceled_order'],
        's_delivery'                   => $data['s_delivery'],
        's_pickup'                     => $data['s_pickup'],
        's_new_order_status'           => $data['s_new_order_status'],
        's_confirm_order_status'       => $data['s_confirm_order_status'],
        's_delivery_assign_status'     => $data['s_delivery_assign_status'],
        's_on_way_status'              => $data['s_on_way_status'],
        's_ecash_used'                 => $data['s_ecash_used'],
        's_cancel_order'               => $data['s_cancel_order'],
        's_confirm_order'              => $data['s_confirm_order'],
        's_assign_delivery'            => $data['s_assign_delivery'],
        's_select_delivery_boy'        => $data['s_select_delivery_boy'],
        's_assign_btn'                 => $data['s_assign_btn'],
        's_order_cancel_msg'           => $data['s_order_cancel_msg'],
        's_order_status_msg'           => $data['s_order_status_msg'],
        's_update_account'             => $data['s_update_account'],
        's_delivery_charges'           => $data['s_delivery_charges'],
        's_enter_km_fix'               => $data['s_enter_km_fix'],
        's_enter_amount_fix'           => $data['s_enter_amount_fix'],
        's_amount_after'               => $data['s_amount_after'],
        's_max_delivery'               => $data['s_max_delivery'],
        's_store_open_close'           => $data['s_store_open_close'],
        's_store_open'                 => $data['s_store_open'],
        's_email_error'                => $data['s_email_error'],
        's_setting_update'             => $data['s_setting_update'],
        's_menu_item'                  => $data['s_menu_item'],
        's_all_item'                   => $data['s_all_item'],
        's_edit'                       => $data['s_edit'],
        's_small_price'                => $data['s_small_price'],
        's_medium_price'               => $data['s_medium_price'],
        's_full_price'                 => $data['s_full_price'],
        's_signup_msg'                 => $data['s_signup_msg'],
        'close'                        => $data['close'],
        'time_period'                  => $data['time_period'],
        'pay_with_cash'                => $data['pay_with_cash'],
        'bank_transfer'                => $data['bank_transfer'],
        'term'                         => $data['term'],
        'term_text'                    => $data['term_text'],
        'my_plan'                      => $data['my_plan'],
        'my_plan_text'                 => $data['my_plan_text'],
        'valid_till'                   => $data['valid_till'],
        'change_plan'                  => $data['change_plan'],
        'select_plan'                  => $data['select_plan'],
        'notes_bank'                   => $data['notes_bank'],
        'my_earn'                      => $data['my_earn'],
        'my_earn_text'                 => $data['my_earn_text'],
        'total_complete_order'         => $data['total_complete_order'],
        'total_earn'                   => $data['total_earn'],
        'from_month'                   => $data['from_month'],
        'eta'                          => $data['eta'],
        'reco'                         => $data['reco'],
        'out_stock'                    => $data['out_stock'],
        'out_stock_msg'                => $data['out_stock_msg'],
        'out_stock_msg_checkout'       => $data['out_stock_msg_checkout'],
        'login_btn'                    => $data['login_btn'],
        'sign_btn'                     => $data['sign_btn'],
        'delivery_title'               => $data['delivery_title'],
        'dinein_title'                 => $data['dinein_title'],
        'location_title'               => $data['location_title'],
        'direction'                    => $data['direction'],
        'contact_no'                   => $data['contact_no'],
        'call_now'                     => $data['call_now'],
        'timing'                       => $data['timing'],
        'avg_per'                      => $data['avg_per'],
        'view_menu'                    => $data['view_menu'],
        'access_page'                  => $data['access_page'],
        'pay_paypal'                   => $data['pay_paypal'],
        'pay_paystack'                 => $data['pay_paystack'],
        'paypal_fail'                  => $data['paypal_fail'],
        'text_paypal_wrong'            => $data['text_paypal_wrong'],
        'd_charge_msg'                 => $data['d_charge_msg'],
        'select_location'              => $data['select_location'],
        'clear'                        => $data['clear'],
        'fast_delivery'                => $data['fast_delivery'],
        'choose_category'              => $data['choose_category'],
        'view_all'                     => $data['view_all'],
        'store_around'                 => $data['store_around'],
        'showing_category'             => $data['showing_category'],
        'filter_by'                    => $data['filter_by'],
        'footer_cart'                  => $data['footer_cart'],
        'footer_profile'               => $data['footer_profile'],
        'your_profile'                 => $data['your_profile'],
        'menu_desc'                    => $data['menu_desc'],
        'conti'                        => $data['conti'],
        'view_account'                 => $data['view_account'],
        'search_res'                   => $data['search_res'],
        'all_store_deliver'            => $data['all_store_deliver'],
        'recent_search_query'          => $data['recent_search_query'],
        'veg'                          => $data['veg'],
        'nonveg'                       => $data['nonveg'],
        'add'                          => $data['add'],
        'cooking_notes'                => $data['cooking_notes'],
        'write_note'                   => $data['write_note'],
        'country'                      => $data['country'],
        'verify_your_email'            => $data['verify_your_email'],
        'verify_your_phone'            => $data['verify_your_phone'],
        'verify_code_sent'             => $data['verify_code_sent'],
        'i_agree'                      => $data['i_agree'],
        'terms'                        => $data['terms'],
        'add_tip'                      => $data['add_tip'],
        'tip_added'                    => $data['tip_added'],
        'address_payment'              => $data['address_payment'],
        'select_delivery_address'      => $data['select_delivery_address'],
        'want_new_address'             => $data['want_new_address'],
        'select_tip'                   => $data['select_tip'],
        'fw'                            => $data['fw'],
        'start_using'                   => $data['start_using'],
        'ecash_use_desc'                => $data['ecash_use_desc'],
        'w_chat'                        => $data['w_chat'],
        'view_less'                     => $data['view_less'],
        'get_started'                   => $data['get_started'],
        'email_us'                      => $data['email_us'],
        'call_us'                       => $data['call_us'],
        'send_msg'                      => $data['send_msg'],
        'any_query'                     => $data['any_query'],
        'your_msg'                      => $data['your_msg'],
        'decline'                       => $data['decline'],
        'you_earn'                      => $data['you_earn'],
        'drop_off'                      => $data['drop_off'],
        'pickup'                        => $data['pickup'],
        'hotspot'                       => $data['hotspot'],
        'edit'                          => $data['edit'],
        'delete'                        => $data['delete'],
        'add_new'                       => $data['add_new'],
        'select_category'               => $data['select_category'],
        'item_name'                     => $data['item_name'],
        'description'                   => $data['description'],
        'item_type'                     => $data['item_type'],
        'both'                          => $data['both'],
        'sort_order'                    => $data['sort_order'],
        'upload_img'                    => $data['upload_img'],
        'new_cate_name'                 => $data['new_cate_name'],
        'opening'                       => $data['opening'],
        'open_now'                      => $data['open_now'],
        'closed_now'                    => $data['closed_now'],
        'your_cart'                     => $data['your_cart'],
        'item_from'                     => $data['item_from'],
        'invoice'                       => $data['invoice'],
        'invoice_desc'                  => $data['invoice_desc'],
        'success'                       => $data['success'],
        'order_success'                 => $data['order_success'],
        'check_order'                   => $data['check_order'],
        'next_step'                     => $data['next_step'],
        'track_order'                   => $data['track_order'],
        'track_desc'                    => $data['track_desc'],
        'view_order_history'            => $data['view_order_history'],
        'whatsapp_desc'                 => $data['whatsapp_desc'],
        'welcome_back'                  => $data['welcome_back'],
        'reset_here'                    => $data['reset_here'],
        'shop_conti'                    => $data['shop_conti'],
        'orders'                        => $data['orders'],
        'parcel'                        => $data['parcel'],
        'total_dis'                     => $data['total_dis'],
        'sender_detail'                 => $data['sender_detail'],
        'rec_detail'                    => $data['rec_detail'],
        'sender_name'                   => $data['sender_name'],
        'sender_phone'                  => $data['sender_phone'],
        'sender_address'                => $data['sender_address'],
        'rec_name'                      => $data['rec_name'],
        'rec_phone'                     => $data['rec_phone'],
        'rec_address'                   => $data['rec_address'],
        'send_parcel'                   => $data['send_parcel'],
        'parcel_title'                  => $data['parcel_title'],
        'parcel_desc'                   => $data['parcel_desc'],
        'what_sending'                  => $data['what_sending'],
        'sender'                        => $data['sender'],
        'rec'                           => $data['rec'],
        'send_later'                    => $data['send_later'],
        'send_package'                  => $data['send_package'],
        'send_package_desc'             => $data['send_package_desc'],
        'acc_term'                      => $data['acc_term'],
        'thanks_tip'                    => $data['thanks_tip'],
        'tip_desc'                      => $data['tip_desc'],
        'ecash_not'                     => $data['ecash_not'],
        'rider_tip'                     => $data['rider_tip'],
        'most_order'                    => $data['most_order'],
        
        ];

        $existingRecord = Text::first();

        if ($existingRecord) {
            $existingRecord->s_data = serialize($allData);
            $existingRecord->save();
        } else {
            $add = new Text;
            $add->s_data = serialize($allData);
            $add->save();
        } 
    }

    public function getSData($index)
    {
    	$res = Text::first();

    	if(isset($res->id))
    	{
    		$sdata = unserialize($res->s_data);

    		return isset($sdata[$index]) ? $sdata[$index] : null;
    	}
    	else
    	{
    		return null;
    	}
    }


    public function getAppData()
    {
        $res = Text::first();
   
        return unserialize($res->s_data);
    }
}
